### PR TITLE
examples/gio-windowing: add macos support

### PR DESCRIPTION
**Pull request by rajveermalviya**

### CODE REVIEW

**Comment by rajveermalviya** [comment]
@gedw99 can you test if it works for you?

**Comment by gedw99** [comment]
@rajveermalviya  your quick....

here goes:

``` 
git clone git@github.com:rajveermalviya/go-webgpu.git -b gio-windowing-macos
Cloning into 'go-webgpu'...
remote: Enumerating objects: 2182, done.
remote: Counting objects: 100% (247/247), done.
remote: Compressing objects: 100% (166/166), done.
remote: Total 2182 (delta 115), reused 182 (delta 74), pack-reused 1935
Receiving objects: 100% (2182/2182), 1.11 GiB | 9.02 MiB/s, done.
Resolving deltas: 100% (1190/1190), done.
Updating files: 100% (100/100), done.

cd go-webgpu/examples/gio-windowing && go build . && ./gio-windowing


```

Screenshot 2022-07-17 at 17 10 34

no errors showing, but blank screen.

**Comment by rajveermalviya** [comment]
can you pull & try again ?

**Comment by gedw99** [comment]
yep doing it....  2 secs

**Comment by gedw99** [comment]
``` 
cd go-webgpu/examples/gio-windowing && go build . && ./gio-windowing
frame
[go-webgpu] [Warn] Unable to get the current view dimensions on a non-main thread
frame
frame
[go-webgpu] [Warn] Unable to get the current view dimensions on a non-main thread
frame
frame
[go-webgpu] [Warn] Unable to get the current view dimensions on a non-main thread
frame
frame
[go-webgpu] [Warn] Unable to get the current view dimensions on a non-main thread
frame
[go-webgpu] [Warn] Unable to get the current view dimensions on a non-main thread
frame
[go-webgpu] [Warn] Unable to get the current view dimensions on a non-main thread
frame

```

Screenshot 2022-07-17 at 17 19 42

when i resize the window, "[go-webgpu] [Warn] Unable to get the current view dimensions on a non-main thread
frame" fires

**Comment by gedw99** [comment]
Its using about 100 MB of ram.

**Comment by rajveermalviya** [comment]
> Its using about 100 MB of ram.

what about glfw triangle example ?

**Comment by gedw99** [comment]
MEM stops growing at 1.67 GB.. 
Screenshot 2022-07-17 at 17 24 36

CPU idles at about 10
Screenshot 2022-07-17 at 17 26 22

**Comment by rajveermalviya** [comment]
and what if you add `runtime.GC()` after [`glfw.PollEvents()`](https://github.com/rajveermalviya/go-webgpu/blob/b9517d523b47e046e6a2529eb6b1dd021d392bf9/examples/triangle/main.go#L205) inside the loop ?

**Comment by gedw99** [comment]
ok 2 secs

**Comment by gedw99** [comment]
``` 
queue := device.GetQueue()
		queue.Submit(encoder.Finish(nil))
		swapChain.Present()

		glfw.PollEvents()
		runtime.GC()
``` 

Mem stable at 25 mb.. 
Screenshot 2022-07-17 at 17 33 54

**Comment by rajveermalviya** [comment]
okay cool, then it's just Go's GC being late to run Finalizers on objects.
guess it's better to [revert back](https://github.com/rajveermalviya/go-webgpu/commit/601f822a2d9a5fda407ecdf480d9c4e36f704f0d) to explicit drops on objects rather than relying on Go's GC.

**Comment by rajveermalviya** [comment]
thank for your help in testing it

**Comment by gedw99** [comment]
No worries. Off to cook BBQ . See ya

**Comment by rajveermalviya** [comment]
> when i resize the window, "[go-webgpu] [Warn] Unable to get the current view dimensions on a non-main thread
frame" fires

for this I think macos doesn't like reconfiguring metal surface in [separate goroutine](https://github.com/rajveermalviya/go-webgpu/blob/b9517d523b47e046e6a2529eb6b1dd021d392bf9/examples/gio-windowing/main.go#L44)

**Comment by gedw99** [comment]
Hey. I am back from holidays Let me know if you want me to test out anything...

**Comment by rajveermalviya** [comment]
> [go-webgpu] [Warn] Unable to get the current view dimensions on a non-main thread
frame 

i did look into this for gio-windowing, i don't think resizing can be fixed given how the gio's api is for now.
because [wgpu](https://github.com/gfx-rs/wgpu) mutates metal surface provided to it when re-configuring swapchain (resizing)
and macos doesn't like it when it's not done from [main thread](https://github.com/rajveermalviya/go-webgpu/blob/b9517d523b47e046e6a2529eb6b1dd021d392bf9/examples/gio-windowing/main.go#L42).

**Comment by gedw99** [comment]
The fact that MacOS wants the main thread to control mutations versus other OS’s that don’t was heavily discussed on the GIOUI issues list. 

I think that a solution can be found if you reach out to them as they are very aware of this problem.

https://todo.sr.ht/~eliasnaur/gio/429

worth raising an issue perhaps ??

**Pull request closed without merging**
